apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: itsonmme
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: itsonmme
    spec:
      containers:
      - name: itsonmme
        image: rajattur/itsonmme
        ports:
        - name: nodejs-port
          containerPort: 3000