apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $SERVICE_NAME
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        image: $IMAGE_NAME
        ports:
        - name: nodejs-port
          containerPort: 3000