apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
  namespace: development
spec:
  ports:
  - port: 80
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: $SERVICE_NAME
  type: LoadBalancer