apiVersion: v1
kind: Service
metadata:
  name: itsonmme-${SERVICE_NAME}
  namespace: development
spec:
  ports:
  - port: 80
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: itsonmme-${SERVICE_NAME}
  type: LoadBalancer