apiVersion: v1
kind: Service
metadata:
  name: itsonmme-{{COMMIT_ID}}
  namespace: development
spec:
  ports:
  - port: 80
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: itsonmme-{{COMMIT_ID}}
  type: LoadBalancer