apiVersion: v1
kind: Service
metadata:
  name: itsonmme
  namespace: development
spec:
  ports:
  - port: 80
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: itsonmme
  type: LoadBalancer